<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DefineConstants>$(DefineConstants);PROJECT_DETAILS_ZETA;PROJECT_DETAILS_ALPHA</DefineConstants>
  </PropertyGroup>
</Project>
