global using AwesomeAssertions;
global using Roslyn.Workbench.Mcp.Plugins.Configuration;
global using Roslyn.Workbench.Mcp.Plugins.Execution;
global using Roslyn.Workbench.Mcp.Plugins.Services;
global using Roslyn.Workbench.Mcp.Plugins.Validation;
global using Roslyn.Workbench.Mcp.Workspace.Resolution;
global using Roslyn.Workbench.Mcp.Workspace.Results;
global using Roslyn.Workbench.Mcp.Workspace.Selectors;
global using Xunit;
