namespace Roslyn.Workbench.Mcp.Workspace.Test.State;

public sealed class WorkspaceErrorCodesTests
{
    [Fact]
    [Trait("Category", "Contract")]
    public void GIVEN_WorkspaceErrorCodes_WHEN_ComparingCompatibilityContract_THEN_ShouldRetainExactValues()
    {
        var actual = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [nameof(WorkspaceErrorCodes.CommitFailed)] = WorkspaceErrorCodes.CommitFailed,
            [nameof(WorkspaceErrorCodes.CommitLockFailed)] = WorkspaceErrorCodes.CommitLockFailed,
            [nameof(WorkspaceErrorCodes.CommitPreparationFailed)] = WorkspaceErrorCodes.CommitPreparationFailed,
            [nameof(WorkspaceErrorCodes.CommitRecoveryCapacity)] = WorkspaceErrorCodes.CommitRecoveryCapacity,
            [nameof(WorkspaceErrorCodes.CompilerValidationIncomplete)] = WorkspaceErrorCodes.CompilerValidationIncomplete,
            [nameof(WorkspaceErrorCodes.CompilerValidationUnavailable)] = WorkspaceErrorCodes.CompilerValidationUnavailable,
            [nameof(WorkspaceErrorCodes.DocumentAmbiguous)] = WorkspaceErrorCodes.DocumentAmbiguous,
            [nameof(WorkspaceErrorCodes.DocumentNotFound)] = WorkspaceErrorCodes.DocumentNotFound,
            [nameof(WorkspaceErrorCodes.DocumentSelectorInvalid)] = WorkspaceErrorCodes.DocumentSelectorInvalid,
            [nameof(WorkspaceErrorCodes.GeneratedSourceMutationDenied)] = WorkspaceErrorCodes.GeneratedSourceMutationDenied,
            [nameof(WorkspaceErrorCodes.InvalidMutationProposal)] = WorkspaceErrorCodes.InvalidMutationProposal,
            [nameof(WorkspaceErrorCodes.InvalidRequest)] = WorkspaceErrorCodes.InvalidRequest,
            [nameof(WorkspaceErrorCodes.LinkedDocumentConflict)] = WorkspaceErrorCodes.LinkedDocumentConflict,
            [nameof(WorkspaceErrorCodes.LocationAmbiguous)] = WorkspaceErrorCodes.LocationAmbiguous,
            [nameof(WorkspaceErrorCodes.LocationNotFound)] = WorkspaceErrorCodes.LocationNotFound,
            [nameof(WorkspaceErrorCodes.LocationSelectorInvalid)] = WorkspaceErrorCodes.LocationSelectorInvalid,
            [nameof(WorkspaceErrorCodes.MutationCandidateChanged)] = WorkspaceErrorCodes.MutationCandidateChanged,
            [nameof(WorkspaceErrorCodes.NewCompilerErrors)] = WorkspaceErrorCodes.NewCompilerErrors,
            [nameof(WorkspaceErrorCodes.ProjectAmbiguous)] = WorkspaceErrorCodes.ProjectAmbiguous,
            [nameof(WorkspaceErrorCodes.ProjectNotFound)] = WorkspaceErrorCodes.ProjectNotFound,
            [nameof(WorkspaceErrorCodes.ProjectSelectorInvalid)] = WorkspaceErrorCodes.ProjectSelectorInvalid,
            [nameof(WorkspaceErrorCodes.RecoveryPending)] = WorkspaceErrorCodes.RecoveryPending,
            [nameof(WorkspaceErrorCodes.SnapshotMismatch)] = WorkspaceErrorCodes.SnapshotMismatch,
            [nameof(WorkspaceErrorCodes.SourceMutationDisabled)] = WorkspaceErrorCodes.SourceMutationDisabled,
            [nameof(WorkspaceErrorCodes.SymbolAmbiguous)] = WorkspaceErrorCodes.SymbolAmbiguous,
            [nameof(WorkspaceErrorCodes.SymbolNotFound)] = WorkspaceErrorCodes.SymbolNotFound,
            [nameof(WorkspaceErrorCodes.SymbolSelectorInvalid)] = WorkspaceErrorCodes.SymbolSelectorInvalid,
            [nameof(WorkspaceErrorCodes.TransactionAlreadyActive)] = WorkspaceErrorCodes.TransactionAlreadyActive,
            [nameof(WorkspaceErrorCodes.TransactionCapacity)] = WorkspaceErrorCodes.TransactionCapacity,
            [nameof(WorkspaceErrorCodes.TransactionConflicted)] = WorkspaceErrorCodes.TransactionConflicted,
            [nameof(WorkspaceErrorCodes.TransactionHistoryUnavailable)] = WorkspaceErrorCodes.TransactionHistoryUnavailable,
            [nameof(WorkspaceErrorCodes.TransactionOpen)] = WorkspaceErrorCodes.TransactionOpen,
            [nameof(WorkspaceErrorCodes.TransactionOwner)] = WorkspaceErrorCodes.TransactionOwner,
            [nameof(WorkspaceErrorCodes.TransactionOwnershipChanged)] = WorkspaceErrorCodes.TransactionOwnershipChanged,
            [nameof(WorkspaceErrorCodes.TransactionReceiptMismatch)] = WorkspaceErrorCodes.TransactionReceiptMismatch,
            [nameof(WorkspaceErrorCodes.TransactionReceiptRequired)] = WorkspaceErrorCodes.TransactionReceiptRequired,
            [nameof(WorkspaceErrorCodes.TransactionRequired)] = WorkspaceErrorCodes.TransactionRequired,
            [nameof(WorkspaceErrorCodes.TransactionReviewUnavailable)] = WorkspaceErrorCodes.TransactionReviewUnavailable,
            [nameof(WorkspaceErrorCodes.UnsupportedChange)] = WorkspaceErrorCodes.UnsupportedChange,
            [nameof(WorkspaceErrorCodes.WorkspaceAlreadyOpen)] = WorkspaceErrorCodes.WorkspaceAlreadyOpen,
            [nameof(WorkspaceErrorCodes.WorkspaceAuthorityChanged)] = WorkspaceErrorCodes.WorkspaceAuthorityChanged,
            [nameof(WorkspaceErrorCodes.WorkspaceBusy)] = WorkspaceErrorCodes.WorkspaceBusy,
            [nameof(WorkspaceErrorCodes.WorkspaceCapacityReached)] = WorkspaceErrorCodes.WorkspaceCapacityReached,
            [nameof(WorkspaceErrorCodes.WorkspaceChangedDuringLoad)] = WorkspaceErrorCodes.WorkspaceChangedDuringLoad,
            [nameof(WorkspaceErrorCodes.WorkspaceExternalDocumentRejected)] = WorkspaceErrorCodes.WorkspaceExternalDocumentRejected,
            [nameof(WorkspaceErrorCodes.WorkspaceInputEvaluationFailed)] = WorkspaceErrorCodes.WorkspaceInputEvaluationFailed,
            [nameof(WorkspaceErrorCodes.WorkspaceLoadFailed)] = WorkspaceErrorCodes.WorkspaceLoadFailed,
            [nameof(WorkspaceErrorCodes.WorkspaceMsBuildPropertiesInvalid)] = WorkspaceErrorCodes.WorkspaceMsBuildPropertiesInvalid,
            [nameof(WorkspaceErrorCodes.WorkspaceNotOpen)] = WorkspaceErrorCodes.WorkspaceNotOpen,
            [nameof(WorkspaceErrorCodes.WorkspaceNotSupported)] = WorkspaceErrorCodes.WorkspaceNotSupported,
            [nameof(WorkspaceErrorCodes.WorkspaceOutOfDate)] = WorkspaceErrorCodes.WorkspaceOutOfDate,
            [nameof(WorkspaceErrorCodes.WorkspacePathInvalid)] = WorkspaceErrorCodes.WorkspacePathInvalid,
            [nameof(WorkspaceErrorCodes.WorkspacePathNotAllowed)] = WorkspaceErrorCodes.WorkspacePathNotAllowed,
            [nameof(WorkspaceErrorCodes.WorkspaceProjectOutsideRoot)] = WorkspaceErrorCodes.WorkspaceProjectOutsideRoot,
            [nameof(WorkspaceErrorCodes.WorkspaceReloadBlocked)] = WorkspaceErrorCodes.WorkspaceReloadBlocked,
            [nameof(WorkspaceErrorCodes.WorkspaceReloadNotRequired)] = WorkspaceErrorCodes.WorkspaceReloadNotRequired,
            [nameof(WorkspaceErrorCodes.WorkspaceRootInvalid)] = WorkspaceErrorCodes.WorkspaceRootInvalid,
            [nameof(WorkspaceErrorCodes.WorkspaceRootNotAllowed)] = WorkspaceErrorCodes.WorkspaceRootNotAllowed,
            [nameof(WorkspaceErrorCodes.WorkspaceSelectorInvalid)] = WorkspaceErrorCodes.WorkspaceSelectorInvalid,
            [nameof(WorkspaceErrorCodes.WorkspaceSelectorMismatch)] = WorkspaceErrorCodes.WorkspaceSelectorMismatch,
            [nameof(WorkspaceErrorCodes.WorkspaceSelectorNotFound)] = WorkspaceErrorCodes.WorkspaceSelectorNotFound,
            [nameof(WorkspaceErrorCodes.WorkspaceSelectorRequired)] = WorkspaceErrorCodes.WorkspaceSelectorRequired,
        };

        var expected = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["CommitFailed"] = "CommitFailed",
            ["CommitLockFailed"] = "CommitLockFailed",
            ["CommitPreparationFailed"] = "CommitPreparationFailed",
            ["CommitRecoveryCapacity"] = "CommitRecoveryCapacityReached",
            ["CompilerValidationIncomplete"] = "CompilerValidationIncomplete",
            ["CompilerValidationUnavailable"] = "CompilerValidationUnavailable",
            ["DocumentAmbiguous"] = "DocumentAmbiguous",
            ["DocumentNotFound"] = "DocumentNotFound",
            ["DocumentSelectorInvalid"] = "DocumentSelectorInvalid",
            ["GeneratedSourceMutationDenied"] = "GeneratedSourceMutationDenied",
            ["InvalidMutationProposal"] = "InvalidMutationProposal",
            ["InvalidRequest"] = "InvalidRequest",
            ["LinkedDocumentConflict"] = "LinkedDocumentConflict",
            ["LocationAmbiguous"] = "LocationAmbiguous",
            ["LocationNotFound"] = "LocationNotFound",
            ["LocationSelectorInvalid"] = "LocationSelectorInvalid",
            ["MutationCandidateChanged"] = "MutationCandidateChanged",
            ["NewCompilerErrors"] = "NewCompilerErrors",
            ["ProjectAmbiguous"] = "ProjectAmbiguous",
            ["ProjectNotFound"] = "ProjectNotFound",
            ["ProjectSelectorInvalid"] = "ProjectSelectorInvalid",
            ["RecoveryPending"] = "RecoveryPending",
            ["SnapshotMismatch"] = "SnapshotMismatch",
            ["SourceMutationDisabled"] = "SourceMutationDisabled",
            ["SymbolAmbiguous"] = "SymbolAmbiguous",
            ["SymbolNotFound"] = "SymbolNotFound",
            ["SymbolSelectorInvalid"] = "SymbolSelectorInvalid",
            ["TransactionAlreadyActive"] = "TransactionAlreadyActive",
            ["TransactionCapacity"] = "RevisionCapacityReached",
            ["TransactionConflicted"] = "TransactionConflicted",
            ["TransactionHistoryUnavailable"] = "TransactionHistoryUnavailable",
            ["TransactionOpen"] = "TransactionOpen",
            ["TransactionOwner"] = "TransactionOwnedByWorkspace",
            ["TransactionOwnershipChanged"] = "TransactionOwnershipChanged",
            ["TransactionReceiptMismatch"] = "TransactionReceiptMismatch",
            ["TransactionReceiptRequired"] = "TransactionReceiptRequired",
            ["TransactionRequired"] = "NoActiveTransaction",
            ["TransactionReviewUnavailable"] = "TransactionReviewUnavailable",
            ["UnsupportedChange"] = "UnsupportedChange",
            ["WorkspaceAlreadyOpen"] = "WorkspaceAlreadyOpen",
            ["WorkspaceAuthorityChanged"] = "WorkspaceAuthorityChanged",
            ["WorkspaceBusy"] = "WorkspaceBusy",
            ["WorkspaceCapacityReached"] = "WorkspaceCapacityReached",
            ["WorkspaceChangedDuringLoad"] = "WorkspaceChangedDuringLoad",
            ["WorkspaceExternalDocumentRejected"] = "WorkspaceExternalDocumentRejected",
            ["WorkspaceInputEvaluationFailed"] = "WorkspaceInputEvaluationFailed",
            ["WorkspaceLoadFailed"] = "WorkspaceLoadFailed",
            ["WorkspaceMsBuildPropertiesInvalid"] = "WorkspaceMsBuildPropertiesInvalid",
            ["WorkspaceNotOpen"] = "WorkspaceNotOpen",
            ["WorkspaceNotSupported"] = "WorkspaceNotSupported",
            ["WorkspaceOutOfDate"] = "WorkspaceOutOfDate",
            ["WorkspacePathInvalid"] = "WorkspacePathInvalid",
            ["WorkspacePathNotAllowed"] = "WorkspacePathNotAllowed",
            ["WorkspaceProjectOutsideRoot"] = "WorkspaceProjectOutsideRoot",
            ["WorkspaceReloadBlocked"] = "WorkspaceReloadBlocked",
            ["WorkspaceReloadNotRequired"] = "WorkspaceReloadNotRequired",
            ["WorkspaceRootInvalid"] = "WorkspaceRootInvalid",
            ["WorkspaceRootNotAllowed"] = "WorkspaceRootNotAllowed",
            ["WorkspaceSelectorInvalid"] = "WorkspaceSelectorInvalid",
            ["WorkspaceSelectorMismatch"] = "WorkspaceSelectorMismatch",
            ["WorkspaceSelectorNotFound"] = "WorkspaceSelectorNotFound",
            ["WorkspaceSelectorRequired"] = "WorkspaceSelectorRequired",
        };

        actual.Should().BeEquivalentTo(expected);
    }
}
