<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.NETCore.Client" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" />
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>
  <ItemGroup>
    <None Update="scenario-suite.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
