global using AwesomeAssertions;
global using Roslyn.Workbench.Mcp.CodeActions.Contracts;
global using Roslyn.Workbench.Mcp.CodeActions.Contracts.Refactorings;
global using Roslyn.Workbench.Mcp.CodeActions.Execution.Results;
global using Roslyn.Workbench.Mcp.IntegrationTestSupport;
global using Roslyn.Workbench.Mcp.Workspace.Lifecycle;
global using Roslyn.Workbench.Mcp.Workspace.Operations;
global using Roslyn.Workbench.Mcp.Workspace.Selectors;
global using Xunit;
