<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Diagnostics.NETCore.Client" Version="0.2.661903" />
    <PackageVersion Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.2.6" />
    <PackageVersion Include="ModelContextProtocol" Version="1.4.1" />
    <PackageVersion Include="JsonSchema.Net" Version="9.4.0" />
  </ItemGroup>
</Project>
